alter table public.editorial_articles add column people_snapshot jsonb not null default '[]'::jsonb check(jsonb_typeof(people_snapshot)='array' and jsonb_array_length(people_snapshot)<=4);
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('editorial-portraits','editorial-portraits',false,5242880,array['image/jpeg','image/png','image/webp']) on conflict(id) do nothing;

create or replace function private.editorial_version() returns trigger language plpgsql security invoker set search_path='' as $$
begin
  if tg_table_name='editorial_issues' then
    if (to_jsonb(new)-array['version','updated_at','previewed_version','published_at','published_version']) is distinct from (to_jsonb(old)-array['version','updated_at','previewed_version','published_at','published_version']) then
      new.version:=old.version+1;
    elsif new.version<>old.version then
      new.version:=old.version+1;
    end if;
  else
    new.version:=old.version+1;
    if (new.title,new.body,new.author,new.department_id,new.event_snapshot,new.people_snapshot) is distinct from (old.title,old.body,old.author,old.department_id,old.event_snapshot,old.people_snapshot) then
      new.status:=case when btrim(new.body)='' then 'draft' else 'review' end;
      new.approved_by:=null;new.approved_at:=null;
    end if;
    if new.status<>'ready' then new.approved_by:=null;new.approved_at:=null;end if;
  end if;
  new.updated_at:=clock_timestamp();
  return new;
end $$;

create or replace function private.editorial_snapshot(target uuid) returns jsonb language sql security invoker set search_path='' as $$
  select jsonb_build_object('schemaVersion',1,'id',i.id,'version',i.version,'title',i.title,'kind',i.kind,'publishes_on',i.publishes_on,
    'advertising',i.advertising,'cover_path',i.cover_path,'cover_alt',i.cover_alt,'cover_credit',i.cover_credit,
    'coverMatches',coalesce((select jsonb_agg(jsonb_build_object(
      'team',case split_part(t.slug,'-',1) when 'herren' then 'Herren' else 'Frauen' end || ' ' ||
        case split_part(t.slug,'-',2) when '1' then 'I' when '2' then 'II' else split_part(t.slug,'-',2) end,
      'articleId',a.id,'date',m.value->>'date','time',nullif(m.value->>'time',''),
      'home',m.value->>'home','away',m.value->>'away',
      'state',case when m.value is not null then 'scheduled' when a.source_snapshot->>'fetchedAt' is not null then 'unavailable' else 'pending' end
    ) order by t.sort_order,t.slug)
      from public.social_teams t
      left join lateral (select sa.id,sa.source_snapshot from public.editorial_articles sa
        where sa.issue_id=i.id and sa.team_id=t.id and sa.kind='sports' order by sa.position,sa.created_at limit 1) a on true
      left join lateral (select value from jsonb_array_elements(coalesce(a.source_snapshot->'upcoming','[]'::jsonb))
        where value->>'scheduled'='true' and coalesce(value->>'finished','false')<>'true'
          and value->>'date'>=i.publishes_on::text
        order by value->>'date',coalesce(value->>'time','') limit 1) m on true
      where t.active and t.slug ~ '^(herren|frauen)-[1-9][0-9]*$'), '[]'::jsonb),
    'articles',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'title',a.title,'body',a.body,'author',a.author,'kind',a.kind,'status',a.status,'automatic_sports',a.automatic_sports,'people',coalesce((select jsonb_agg(jsonb_build_object('name',p->>'name','role',p->>'role','photo_path',p->>'photo_path')) from jsonb_array_elements(a.people_snapshot) p),'[]'::jsonb),'event',a.event_snapshot-array['description','source_id']) order by a.position,a.created_at) from public.editorial_articles a where a.issue_id=i.id),'[]'::jsonb))
  from public.editorial_issues i where i.id=target;
$$;

-- Fill missing catalogue functions and coaching memberships from the existing website catalogue.
insert into public.social_people(slug,display_name,roles,source_photo_url) values('alexander-kaiser','Alexander Kaiser',array['Trainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('alexander-kramer','Alexander Kramer',array['Trainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('andrea-basile','Andrea Basile',array['Co-Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/andrea-basile.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('andreas-wolfmuller','Andreas Wolfmüller',array['Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/andreas-wolfmueller.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('axel-schauble','Axel Schäuble',array['Cheftrainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/axel-schaeuble.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('christoph-pabst','Christoph Pabst',array['Trainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('dana-bulander','Dana Bulander',array['Trainerin','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/dana-bulander.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('elias-arfa','Elias Arfa',array['Trainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('emel-bayram','Emel Bayram',array['Co-Trainerin','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/emel-bayram.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('fabian-keller','Fabian Keller',array['Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/fabian-keller.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('felix-schule','Felix Schüle',array['2. Vorstand','Spieler:in','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/felix-schuele.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('frieder-demmer','Frieder Demmer',array['Athletik- und Fitnesscoach','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/frieder-demmer.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('hieu-ho','Hieu Ho',array['Co-Trainerin']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('humberto-vicente-agudo-torres','Humberto Vicente Agudo Torres',array['Trainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('jerome-ernsberger','Jérôme Ernsberger',array['Jugendleiter','Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/jerome-ernsberger.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('jorg-boreatti','Jörg Boreatti',array['Spieler:in','Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/joerg-boreatti.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('luca-gastaudo','Luca Gastaudo',array['Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/luca-gastaudo.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('marcelino-ruth','Marcelino Rüth',array['Trainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('marco-tassone','Marco Tassone',array['Trainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('marko-eisner','Marko Eisner',array['Co-Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/marco-eisner.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('marlia-burlander','Marlia Burlander',array['Trainerin','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/marlia-burlander.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('mathias-becht','Mathias Becht',array['Spieler:in','Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/mathias-becht.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('max-menzel','Max Menzel',array['Co-Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/max-menzel.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('maximilian-geismann','Maximilian Geismann',array['Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/maximilian-geismann.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('michael-jentsch','Michael Jentsch',array['Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/migo-jentsch.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('michael-meiss','Michael Meiss',array['Trainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('michael-sick','Michael Sick',array['Trainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('mila-ernsberger','Mila Ernsberger',array['Trainerin','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/mila-ernsberger.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('mohamad-mahmoudi','Mohamad Mahmoudi',array['Trainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('myriam-lipp','Myriam Lipp',array['Chef-Trainerin','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/myriam-lipp.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('niku-pourheidari','Niku Pourheidari',array['Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/niku-pourheidari.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('noemi-sophie-friedrich','Noemi Sophie Friedrich',array['Trainerin','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/noemi-sophie-friedrich.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('ole-schmal','Ole Schmal',array['Co-Trainer','Stellvertretender Jugendleiter']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('pascal-dieterle','Pascal Dieterle',array['Trainer']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/pascal-dieterle.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('patrick-muller','Patrick Müller',array['Co-Trainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('sandra-fuchs','Sandra Fuchs',array['1. Vorstand','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/sandra-fuchs.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('sebastian-bauerle','Sebastian Bäuerle',array['Cheftrainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('simon-buhler','Simon Bühler',array['Co-Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/simon-buehler.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('sina-rauch','Sina Rauch',array['Trainerin','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/sina-rauch.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('sonja-thomen','Sonja Thomen',array['Co-Trainerin']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('stefan-sulger','Stefan Sulger',array['Trainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('stephan-hellmann','Stephan Hellmann',array['Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/stephan-hellmann.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('sven-goldhagen','Sven Goldhagen',array['Cheftrainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/sven-goldhagen.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('thomas-parthenschlager','Thomas Parthenschlager',array['Co-Trainer']::text[],null) on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('torben-altenburg','Torben Altenburg',array['Co-Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/torben-altenburg.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_people(slug,display_name,roles,source_photo_url) values('torsten-parzich','Torsten Parzich',array['Trainer','Vereinsmitglied']::text[],'https://gerinjo.github.io/bsv-website/images/verein/personen/torsten-parzich.jpg') on conflict(slug) do update set roles=(select array_agg(distinct role order by role) from unnest(public.social_people.roles || excluded.roles) role);
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='herren-1' and p.slug='torsten-parzich' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Co-Trainer' from public.social_teams t,public.social_people p where t.slug='herren-1' and p.slug='torben-altenburg' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='herren-2' and p.slug='alexander-kaiser' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='frauen-1' and p.slug='mathias-becht' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Co-Trainer' from public.social_teams t,public.social_people p where t.slug='frauen-1' and p.slug='max-menzel' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Chef-Trainerin' from public.social_teams t,public.social_people p where t.slug='frauen-2' and p.slug='myriam-lipp' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Co-Trainerin' from public.social_teams t,public.social_people p where t.slug='frauen-2' and p.slug='emel-bayram' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u19-junioren' and p.slug='michael-jentsch' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Co-Trainer' from public.social_teams t,public.social_people p where t.slug='u19-junioren' and p.slug='ole-schmal' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Athletik- und Fitnesscoach' from public.social_teams t,public.social_people p where t.slug='u19-junioren' and p.slug='frieder-demmer' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u17-junioren' and p.slug='maximilian-geismann' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Co-Trainer' from public.social_teams t,public.social_people p where t.slug='u17-junioren' and p.slug='andrea-basile' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Cheftrainer' from public.social_teams t,public.social_people p where t.slug='u15-c1-junioren' and p.slug='axel-schauble' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Co-Trainer' from public.social_teams t,public.social_people p where t.slug='u15-c1-junioren' and p.slug='simon-buhler' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Co-Trainer' from public.social_teams t,public.social_people p where t.slug='u15-c1-junioren' and p.slug='thomas-parthenschlager' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Cheftrainer' from public.social_teams t,public.social_people p where t.slug='u15-c2-junioren' and p.slug='sebastian-bauerle' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u13-d1-junioren' and p.slug='stephan-hellmann' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Co-Trainerin' from public.social_teams t,public.social_people p where t.slug='u13-d1-junioren' and p.slug='hieu-ho' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u13-d2-junioren' and p.slug='jorg-boreatti' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Co-Trainer' from public.social_teams t,public.social_people p where t.slug='u13-d2-junioren' and p.slug='marko-eisner' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Co-Trainer' from public.social_teams t,public.social_people p where t.slug='u13-d2-junioren' and p.slug='patrick-muller' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u13-d3-junioren' and p.slug='jerome-ernsberger' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u11-e1-junioren' and p.slug='niku-pourheidari' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u11-e1-junioren' and p.slug='christoph-pabst' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u11-e2-junioren' and p.slug='marcelino-ruth' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u11-e2-junioren' and p.slug='mohamad-mahmoudi' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u11-e3-junioren' and p.slug='stefan-sulger' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u11-e3-junioren' and p.slug='michael-sick' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u9-f-junioren' and p.slug='andreas-wolfmuller' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainerin' from public.social_teams t,public.social_people p where t.slug='u9-f-junioren' and p.slug='sina-rauch' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u9-f-junioren' and p.slug='marcelino-ruth' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u8-f-junioren' and p.slug='pascal-dieterle' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u8-f-junioren' and p.slug='fabian-keller' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u8-f-junioren' and p.slug='humberto-vicente-agudo-torres' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u7-bambinis' and p.slug='michael-meiss' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u7-bambinis' and p.slug='luca-gastaudo' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u7-bambinis' and p.slug='marco-tassone' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u6-spielgruppe' and p.slug='elias-arfa' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainerin' from public.social_teams t,public.social_people p where t.slug='u6-spielgruppe' and p.slug='noemi-sophie-friedrich' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainerin' from public.social_teams t,public.social_people p where t.slug='u6-spielgruppe' and p.slug='mila-ernsberger' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainerin' from public.social_teams t,public.social_people p where t.slug='u6-spielgruppe' and p.slug='marlia-burlander' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Cheftrainer' from public.social_teams t,public.social_people p where t.slug='u17-juniorinnen' and p.slug='sven-goldhagen' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Co-Trainerin' from public.social_teams t,public.social_people p where t.slug='u17-juniorinnen' and p.slug='sonja-thomen' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainer' from public.social_teams t,public.social_people p where t.slug='u15-juniorinnen' and p.slug='alexander-kramer' on conflict do nothing;
insert into public.social_team_people(team_id,person_id,role) select t.id,p.id,'Trainerin' from public.social_teams t,public.social_people p where t.slug='u13-juniorinnen' and p.slug='dana-bulander' on conflict do nothing;
